spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: "{cipher}AQCP1KPgqcpx498qNwncOTIZrqfNFfCQPnKVypAECx17H/dAqow+FuU9O/CCEjgLSwYUc6EKRs9XGqTS0AiYEq6+7kZ0hhsKNEWg1DBAVx+4C/mU0jCVdXeJUIv62iu0t/i+4OVq9Kb41zLDQvVspxYBDM3bFYxYwR2RoSqTG8wwB23uAr6ilTjM+JaUCjP+QP6Ju2PAvuMoKbU7TvxJruadnWBq8ee+SLO307zzomae/fXcDoENK3syftVzJVK1YoFPt+m5uoU4BBj2aRpBo2pJcuxb0dF051kHRa9ealRjID9M8aC/rxLi4evM1GaWym9jxQ34PtPxSitlOH1+P5vQjIKednBuveUoHE/PKrrft8q7KfpVnUZJhWmCkjs+wF8="

token:
  expiration_time: 864000000
  secret: user_token_more_than_128bit

gateway:
  ip: 192.168.0.8

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.
